languageCode = "pt-br"
languageName = "Brasillll"
weight = 1
title = "Lucas F. Guanabara"

[params]
  displayName = "PT-BR"
  isoCode = "pt-br"
  rtl = false
  dateFormat = "02/01/2006"
  logo = "img/logo1.png"
  secondaryLogo = "img/logo-inverted.png"
  description = "Lucas Portfolio"
  # copyright = "Copy, _right?_ :thinking_face:"


[author]
  name = "Lucas F. Guanabara"
  image = "img/lucas-home.jpeg"
  headline = "Estudante de T.I | Desenvolvedor Fullstack | Entusiasta de CyberSec"
  bio = "Sinta-se à vontade para explorar meu site e acompanhar minha evolução nesse mundo em constante transformação!."
  links = [
    { github = "https://github.com/printflucasguanabara" },
    { linkedin = "https://www.linkedin.com/in/lucas-f-guanabara-1a688b1b7/" },
    { codepen = "https://codepen.io/printflucasguanabara" },
    { email = "mailto:lucasff.guanabara@gmail.com"},
    { code ="https://app.daily.dev/lucasfguanabara"},
    { google = "https://developers.google.com/profile/u/lucasguanabara?authuser=1"}

  ]

